### PR TITLE
Add infix operation evaluation

### PR DESCRIPTION
**Pull request by mmiranda96**
# What does this PR do?
Contribute to #1 by adding an infix operation evaluator. It basically takes an expression like `(1+2) / 3 * (5 * 6.88) - 12` and evaluates it. This is a great algorithm and a very extensive implementation, since it involves:
- Linked list
- Stack (built over a linked list)
- Queue (built over two stacks)
- Infix to prefix parsing
- Prefix evaluation

My original source and more algorithms can be found [here](https://github.com/mmiranda96/algorithms-go).

### CODE REVIEW

**Comment by mmiranda96** [comment]
Did I forget to mention it includes tests with 100% coverage :smile:?

**Comment by abranhe** [comment]
Thank you for contributing to [@AllAlgorithms](https://github.com/AllAlgorithms/) ✨ Make sure that you ⭐️ the project 🤓, and continue helping us!

[img](https://github.com/allalgorithms/go)

We are very happy with your contribution, but for the pull request to got merged in, we should fix the following:

- [ ] Implement the algorithm in one file. What about a simple `fmt.Println()` 😃
- [ ] change the algorithms to their respective folder according to the type, Eg: `stack.go` can be moved to `/data-scructures/stack.go/` istead of `opeval`.

**Comment by mmiranda96** [comment]
Changes done :smile:

**Comment by abranhe** [comment]
Since https://github.com/AllAlgorithms/go/pull/10#issuecomment-426569164 We have decided to organize as follow this repository:

```
├── searching
│   ├── binary
│   │   ├── search.go
│   │   └── search_test.go
│   └── linear
│       ├── search.go
│       └── search_test.go
└── sorting
    ├── bubble
    │   ├── sort.go
    │   └── sort_test.go
    └── merge
        ├── sort.go
        └── sort_test.go
```

So, would you mind take a look again and make a few changes to follow the new style. You will end up with somting like this:

```
├── data-structures
    ├── stack
    │   ├── stack.go
    │   └── stack_test.go
    └── list
        ├── list.go
        └── list_test.go
```

Also, would you move the Operation Evaluation from `/opeval` to `/others`

**Comment by mmiranda96** [comment]
Fixed! I'll leave the data structures package as `datastructures`, since Go packages can't have hyphens and `data_structures` isn't idiomatic.

**Comment by abranhe** [comment]
@mmiranda96 This isn't a Go package, but since the community on Github have been requested to make it like that, why not right!

The pull request will be merged! Don't forget to give us a start!

**Pull request merged**
