### PR TITLE
Add quick sort algorithm

### PR DESCRIPTION
**Pull request by marekfilip**
Add quick sort algorithm according to issue #1.

### CODE REVIEW

**Comment by abranhe** [comment]
Thank you for contributing to [@AllAlgorithms](https://github.com/AllAlgorithms/), your pr got merged! ✨ Make sure that you ⭐️ the project 🤓, and continue helping us!

[img](https://github.com/allalgorithms/go)

We are very happy with your contribution, but for the pull request to got merged in, we should fix the following:

- [ ] Implement the algorithm in one file. What about a simple `fmt.Println()` 😃

**Comment by Sata51** [comment]
@abranhe Unit test is really important, and in go, it must be located in a different file to be run. You should consider allowing two file for each algorithm.
One for the algorithm and another for test.

**Comment by abranhe** [comment]
@Sata51 Thanks for the heads up! I am not a Go developer so definetly I have to follow what should done! But this isn't a go libray, just algorithms implementations, so that's why I didn't wanted to add a `_test.go` file for each algorithm.

So, what do you think about creating a `/test` directory to implement the tests in a diferent folder? Like so:

```
├── sorting
│   ├── bubblesort.go
│   └── mergesort.go
├── searching
│   ├── binarysearch.go
│   └── linearsearch.go
└── tests
    ├── sorting
    │   ├── bubblesort_test.go
    │   └── mergesort_test.go
    └── searching
        ├── binarysearch.go_test.go
        └── linearsearch.go_test.go
```

Ideas please!!!! @Sata51

**Comment by Sata51** [comment]
@abranhe Following the language best practice for testing purpose you should :

From [golang test](https://golang.org/pkg/testing/):
"To write a new test suite, create a file whose name ends _test.go that contains the TestXxx functions as described here. Put the file in the same package as the one being tested. The file will be excluded from regular package builds but will be included when the “go test” command is run. For more detail, run “go help test” and “go help testflag”."

So, for this, we should write something like this:
```
├── searching
│   ├── binary
│   │   ├── search.go
│   │   └── search_test.go
│   └── linear
│       ├── search.go
│       └── search_test.go
└── sorting
    ├── bubble
    │   ├── sort.go
    │   └── sort_test.go
    └── merge
        ├── sort.go
        └── sort_test.go
```

**Comment by marekfilip** [comment]
As @Sata51 said, if we want to have test files we should stay with Go best practices and folder structure.
Second thought is that now, there will be several main function in one package. That's bad :-1: We are unable to `go get` this repository now. After merge pr #3, #5, #7 if you try `go get github.com/AllAlgorithms/go/sorting` you will get 
```
go get github.com/AllAlgorithms/go/sorting

# github.com/AllAlgorithms/go/sorting
go/sorting/insertion_sort.go:9:6: main redeclared in this block
        previous declaration at go/sorting/bubble_sort.go:8:6
go/sorting/merge_sort.go:7:6: main redeclared in this block
        previous declaration at go/sorting/insertion_sort.go:9:6
go/sorting/shell_sort.go:11:6: main redeclared in this block
        previous declaration at go/sorting/merge_sort.go:7:6
```

**Comment by Sata51** [comment]
Package must be rename in all files and all folder must be treat as a library. With the new file tree a user must `go get github.com/AllAlgorithms/go/sorting/bubble`

and use this like this:
```go
package myPackage
import "github.com/AllAlgorithms/go/sorting/bubble"

func main(){
    arr := []int{46, 24, 33, 10, 2, 81, 50}
    bubble.Sort(arr)
}
```

**Comment by abranhe** [comment]
@marekfilip  @Sata51 I still not sure about this one, because making a directory with a bunch of algorithms and tests will be a mess. I never thought about making a library out of this, we could do so but yeap we will have to make a new directory for each algorithm, that will be clean and neat.

I think we should do what's best for the community, and making tests will do so!

**Comment by abranhe** [comment]
This pull request will be closed since #13

**Pull request closed without merging**
